### ISSUE TITLE
Fails to parse query params that are also URLs

### ISSUE THREAD

**Issue by jamesfzhang** [boo1ean/shitty-qs#1]
The URL is `/app?redirect=/home?referrer=ad`. The `redirect` query param is a URL itself with its own query string. The correct value for `redirect` should be `/home?referrer=ad` but this library parses it to be `/home?referrer`. Thoughts?

**Comment by boo1ean** [comment]
Normally url in param should be url-encoded `%2Fhome%3Freferrer%3Dad` [reference](http://www.w3schools.com/tags/ref_urlencode.asp)

This result is predictable for current implementation.
https://github.com/boo1ean/shitty-qs/blob/master/index.js#L21-L23

You can try to work around it by joining all tokens starting from index 1 and treat it as value.

PR is welcomed.

**Comment by jamesfzhang** [comment]
Okay thanks!
